---
title: "Innovation and uncertainty"
---

Last month YEAQ hosted its second event for 2018, featuring a panel discussion on _innovating with uncertainty._ 

The panel was as diverse as the sources of uncertainty facing Australian engineers, and the discussion went some places I don't think anyone was expecting.

The evening launched and landed on Mars with the final question - a crowd favourite - transcending planetary distinction. It could be applied just as easily to cities here on Earth as to the barren martian lands.

> "So let’s say we go to Mars in 10 years and have the chance to build a new city, from the ground up, what is the _one_ thing you would like to see in that city?"

We thought it was important to capture some of the key messages and provide you with this brief summary so you can take a moment, step back, think big and consolidate your learnings.\
\
\
Why this topic at this moment in time? Well, a lot of companies (not just in engineering) are faced with an issue as Julie Mitchell wisely put,

> _"there's actually a risk in not innovating, a huge risk"_

